export const LANGUAGES = ["th", "en", "zh-CN", "zh-TW", "vi"];
export const LANGUAGE_LABELS = { th:"ไทย", en:"English", "zh-CN":"简体中文", "zh-TW":"繁體中文", vi:"Tiếng Việt" };
export const SCAN_INTERVAL_MS = 45 * 60 * 1000;
export const COMMENT_GAP_MS = 5 * 60 * 1000;
export const SESSION_TTL_MS = 7 * 24 * 60 * 60 * 1000;
export const PENDING_LOGIN_TTL_MS = 10 * 60 * 1000;
export function validateRule(rule){if(!rule||typeof rule!=="object")throw new Error("Rule is required");if(!rule.accountId)throw new Error("accountId is required");if(!rule.channelId)throw new Error("channelId is required");if(!LANGUAGES.includes(rule.outputLanguage))throw new Error("Unsupported output language");if(!["ai","template"].includes(rule.mode))throw new Error("Unsupported comment mode");if(rule.mode==="template"&&!String(rule.templateText||"").trim())throw new Error("Template text is required");return true;}
export function normalizePostText(message){return String(message?.message??message?.text??"").trim();}
export function scheduleJobs(posts,startAt,existingJobs=[],gapMs=COMMENT_GAP_MS){const activeDue=existingJobs.filter(j=>["queued","processing"].includes(j.status)).map(j=>Number(j.dueAt||0));const next=Math.max(Number(startAt),activeDue.length?Math.max(...activeDue)+gapMs:Number(startAt));return posts.map((post,index)=>({...post,dueAt:next+index*gapMs}));}
export function isScanDue(lastScanAt,now){return !lastScanAt||Number(now)-Number(lastScanAt)>=SCAN_INTERVAL_MS;}
export function pickTemplate(templateText,seed=0){const parts=String(templateText||"").split(/\n\s*---\s*\n/g).map(s=>s.trim()).filter(Boolean);if(!parts.length)throw new Error("No template text available");return parts[Math.abs(Number(seed||0))%parts.length];}
export function buildGeminiBody({postText,outputLanguage,instruction="",model}){if(!LANGUAGES.includes(outputLanguage))throw new Error("Unsupported output language");const language=LANGUAGE_LABELS[outputLanguage];const system=["You write one short, natural Telegram discussion comment about a news post.",`Output language: ${language}.`,"Read and understand the source even when it is written in another language.","Do not invent facts, names, numbers, or claims that are absent from the source.","Do not repeat the headline verbatim. Do not include URLs or @mentions unless the source requires them.","Return only the comment text, no JSON, labels, markdown, or quotation marks.",instruction?`Additional style instruction: ${instruction}`:""].filter(Boolean).join("\n");return{model,body:{systemInstruction:{parts:[{text:system}]},contents:[{role:"user",parts:[{text:`SOURCE POST:\n${String(postText||"").slice(0,12000)}`}]}],generationConfig:{temperature:.75,maxOutputTokens:180}}};}
export function parseGemini(data){const text=data?.candidates?.[0]?.content?.parts?.map(p=>p?.text||"").join("").trim();if(!text)throw new Error("Gemini returned no comment");return text.replace(/^['\"“”]+|['\"“”]+$/g,"").trim();}
export function safeComment(text){const value=String(text||"").trim();if(!value)throw new Error("Comment is empty");if(value.length>800)throw new Error("Comment is too long");return value;}
export function newId(prefix="id"){return `${prefix}_${crypto.randomUUID()}`;}
